FROM node:20-alpine AS build
WORKDIR /app
COPY frontend/cloud-crypto/package*.json .
RUN npm ci
COPY frontend/cloud-crypto/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist/cloud-crypto/browser /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
